# Generated by Django 3.1.7 on 2021-03-29 16:06
# keepin' Black happy by manually saving...

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccinstContLink",
            fields=[
                ("cont_cn", models.CharField(max_length=34)),
                ("link_type_name", models.CharField(max_length=40)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("leading_ind", models.CharField(blank=True, max_length=1, null=True)),
                ("department", models.CharField(blank=True, max_length=40, null=True)),
                ("division", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "ffis_vendor_id_pre_fmmi",
                    models.CharField(
                        blank=True,
                        help_text="The cooperator/recipient's VEND number as assigned by FMMI.",
                        max_length=11,
                        null=True,
                        verbose_name="FMMI Vendor ID",
                    ),
                ),
                (
                    "faads_addr_cn",
                    models.CharField(blank=True, max_length=34, null=True),
                ),
                (
                    "institution_code",
                    models.CharField(
                        blank=True,
                        help_text="\n            The institution code for State Controlled Institution of Higher Learning only.\n            Required if FFATA reported.\n        ",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "fed_debt_delnqnt_ind",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        help_text="\n            Check this box to indicate if the applicant is delinquent on any federal debt.\n        ",
                        max_length=1,
                        null=True,
                        verbose_name="Delinquent on Fed. Debt",
                    ),
                ),
                (
                    "payee_ind",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        null=True,
                        verbose_name="Payee",
                    ),
                ),
                (
                    "applicant_ind",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "link_sub_type",
                    models.CharField(
                        blank=True,
                        help_text="\n            Indicates the type of contact, for example, FS Signatory Official (SO) or Reviewer (RW),\n            depending on the responsibility/role the contact has with the instrument.\n        ",
                        max_length=40,
                        null=True,
                        verbose_name="Sub Type",
                    ),
                ),
                (
                    "cn",
                    models.CharField(max_length=34, primary_key=True, serialize=False),
                ),
                (
                    "ffis_can_number_status",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("payer_ind", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "fmmi_customer_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "ffis_vendor_id",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "fmmi_customer_number_status",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("sam_expiration_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "ii_accinst_cont_links",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AccomplishmentInstrument",
            fields=[
                (
                    "cn",
                    models.CharField(max_length=34, primary_key=True, serialize=False),
                ),
                ("id", models.CharField(max_length=40)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("obj_tech", models.CharField(max_length=30)),
                ("obj_name", models.CharField(max_length=30)),
                ("obj_class", models.CharField(max_length=30)),
                (
                    "managing_cont_cn",
                    models.CharField(blank=True, max_length=34, null=True),
                ),
                (
                    "replaced_by_ai_cn",
                    models.CharField(blank=True, max_length=34, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                ("exp_expiration_date", models.DateField(blank=True, null=True)),
                (
                    "tim_allow_updates",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "tim_contract_no",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("tim_region", models.CharField(blank=True, max_length=2, null=True)),
                ("tim_forest", models.CharField(blank=True, max_length=2, null=True)),
                ("tim_district", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "acbladd_bill_address_id",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                ("trans_id", models.CharField(blank=True, max_length=34, null=True)),
                ("created_by", models.CharField(max_length=30)),
                ("created_date", models.DateField()),
                (
                    "created_in_instance",
                    models.DecimalField(decimal_places=0, max_digits=6),
                ),
                ("modified_by", models.CharField(blank=True, max_length=30, null=True)),
                ("modified_date", models.DateField(blank=True, null=True)),
                (
                    "modified_in_instance",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=6, null=True
                    ),
                ),
                (
                    "master_site",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=6, null=True
                    ),
                ),
                ("security_id", models.CharField(max_length=30)),
                ("agency_code", models.CharField(blank=True, max_length=4, null=True)),
                ("parent_cn", models.CharField(blank=True, max_length=34, null=True)),
            ],
            options={
                "db_table": "accplishment_instruments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AdminUnit",
            fields=[
                (
                    "admin_unit_cn",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("fs_unit_id", models.CharField(max_length=4)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=255)),
                (
                    "parent_unit_fk",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("last_update", models.DateField()),
            ],
            options={
                "db_table": "admin_units",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "cn",
                    models.CharField(
                        editable=False, max_length=34, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        help_text="\n            For new Contacts, this field is a system generated number.\n            For older contacts it will be a shortened version of the contact's full name or organization title.\n        ",
                        max_length=30,
                        verbose_name="Contact ID",
                    ),
                ),
                (
                    "obj_tech",
                    models.CharField(default="ORACLE", editable=False, max_length=30),
                ),
                (
                    "obj_name",
                    models.CharField(
                        default="ORGANIZATION", editable=False, max_length=30
                    ),
                ),
                (
                    "obj_class",
                    models.CharField(default="CONTACT", editable=False, max_length=30),
                ),
                (
                    "created_by",
                    models.CharField(
                        editable=False,
                        help_text="Should capture username.",
                        max_length=30,
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "created_in_instance",
                    models.DecimalField(decimal_places=0, editable=False, max_digits=6),
                ),
                (
                    "trans_id",
                    models.CharField(
                        blank=True, max_length=34, null=True, verbose_name="Trans ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Contact's Last Name, First Name",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "master_site",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=6, null=True
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="Any comments regarding the contact or cooperator.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Should capture username.",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("modified_date", models.DateField(auto_now=True, null=True)),
                (
                    "modified_in_instance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        editable=False,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "security_id",
                    models.CharField(
                        blank=True, editable=False, max_length=30, null=True
                    ),
                ),
                ("agency_code", models.CharField(max_length=4)),
                (
                    "admin_org_ind",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        max_length=1,
                        verbose_name="Admin Org",
                    ),
                ),
                (
                    "ein",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Employer Identification Number.",
                        max_length=40,
                        null=True,
                        verbose_name="EIN",
                    ),
                ),
                (
                    "duns",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="\n            The identification number assigned to the cooperator/recipient by the\n            Dun and Bradstreet Data Universal Numbering System (DUNS).\n            Call 1-866-705-5711 or visit the DUNS Number Request Form to request and register for a DUNS number.\n        ",
                        max_length=40,
                        null=True,
                        verbose_name="DUNS",
                    ),
                ),
                (
                    "faads_cn",
                    models.CharField(
                        blank=True, editable=False, max_length=34, null=True
                    ),
                ),
                (
                    "ffis_vendor_status",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="FFIS vendor status",
                    ),
                ),
                (
                    "alc_code",
                    models.CharField(
                        blank=True,
                        help_text="The Agency Location Code.",
                        max_length=40,
                        null=True,
                        verbose_name="ALC",
                    ),
                ),
                (
                    "parent_duns",
                    models.CharField(
                        blank=True,
                        help_text="\n            The identification number assigned to the cooperator/recipient by the\n            Dun and Bradstreet Data Universal Numbering System (DUNS).",
                        max_length=40,
                        null=True,
                        verbose_name="Parent DUNS",
                    ),
                ),
                (
                    "duns_confidence_cd",
                    models.CharField(
                        blank=True,
                        help_text="Confidence Code assigned via SAM validation.",
                        max_length=2,
                        null=True,
                        verbose_name="DUNS Confidence Score",
                    ),
                ),
                (
                    "international",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "archived_flag",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")], default="N", max_length=1
                    ),
                ),
                (
                    "office_hours",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
            options={
                "db_table": "ii_contacts",
                "managed": False,
            },
        ),
    ]
