# Generated by Django 3.2.4 on 2021-07-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accinstcontlink',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='accomplishmentinstrument',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='adminunit',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False},
        ),
    ]
