services:

  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # command: pipenv run ./manage.py migrate --settings=nrm_site.settings.dev

  api:
    build: ./api
    volumes:
      - ./api:/code
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run serve
    depends_on:
      - postgres

  web:
    build: ./frontend
    volumes:
      - ./frontend:/code
    expose:
      - "4200"
    ports:
      - "4200:4200"
    command: npm run start
    depends_on:
      - api
