# Generated by Django 3.1.7 on 2021-03-10 18:05. Formatted by Black.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="international_act_ind",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                max_length=1,
                null=True,
                verbose_name="International Act",
            ),
        ),
    ]
