# Generated by Django 3.1.7 on 2021-03-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0005_auto_20210310_1825"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="grant_cn",
        ),
        migrations.AddField(
            model_name="note",
            name="grant",
            field=models.ForeignKey(
                db_column="grant_cn",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="grants.grant",
            ),
            preserve_default=False,
        ),
    ]
