# Generated by Django 3.1.7 on 2021-03-24 20:03
# comment to make Black format and not complain

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0007_auto_20210323_1321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="advance_allowed_ind",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                help_text="Indicates if advanced payments are allowed in the instrument. Select Y if advanced payments are allowed.",
                max_length=1,
                null=True,
                verbose_name="Advance Allowed",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="aop_ind",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                help_text="\n            Select Yes from the choice list if the instrument requires an Annual Operating Plan (AOP); \n            select Yes if the instrument requires an AOP.\n        ",
                max_length=1,
                null=True,
                verbose_name="AOP",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="app_received_date",
            field=models.DateField(
                help_text="The date the proposal was received by the Forest Service.",
                verbose_name="Application received",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="app_submission_type",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("Application", "Application"),
                    ("Preapplication", "Pre-application"),
                    (
                        "NON-CONSTRUCTION PRE-APPLICATION",
                        "Non-construction Pre-application",
                    ),
                    ("NON-CONSTRUCTION APPLICATION", "Non-construction Application"),
                    ("CONSTRUCTION PRE-APPLICATION", "Construction Pre-application"),
                    ("CONSTRUCTION APPLICATION", "Construction Application"),
                    ("MOU", "Mou"),
                    ("OTHER", "Other"),
                    (
                        "8/1/2004NON-CONSTRUCTION APPLICATION",
                        "8/1/2004NON-CONSTRUCTION APPLICATION",
                    ),
                    (
                        "5/1/2005NON-CONSTRUCTION APPLICATION",
                        "5/1/2005NON-CONSTRUCTION APPLICATION",
                    ),
                ],
                help_text="\n            Applies to instruments with Federal Financial Assistance (FFA). \n            Select OTHER if not FFA.\n        ",
                max_length=100,
                verbose_name="Type of Submission",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="app_submit_date",
            field=models.DateField(
                help_text="The date the proposal was submitted to the agreements specialist for review or processing.",
                verbose_name="Application submitted",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CONTINUATION", "Continuation"),
                    ("REVISION A-INCREASE AWARD", "Revision A - Increase Award"),
                    ("REVISION B-DECREASE AWARD", "Revision B - Decrease Award"),
                    ("REVISION C-INCREASE AWARD", "Revision C - Increase Duration"),
                    ("REVISION D-DECREASE AWARD", "Revision D - Decrease Duration"),
                    ("OTHER", "Other"),
                ],
                help_text="\n            Applies to instruments with Federal Financial Assistance (FFA). \n            Select OTHER if not FFA.\n        ",
                max_length=30,
                verbose_name="Type of application",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="areas_effected",
            field=models.CharField(
                blank=True,
                help_text="\n            Areas (states, localities, congressional districts, and other areas) that are affected by the project.\n        ",
                max_length=200,
                null=True,
                verbose_name="Areas Affected",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="cn",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="A system-generated number used to identify the proposal before an agreement number is assigned or the instrument is executed.",
                max_length=34,
                primary_key=True,
                serialize=False,
                verbose_name="Proposal ID",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="cooperator_agreement_number",
            field=models.CharField(
                blank=True,
                help_text="Cooperators agreement number, if different then the Forest Service Agreement Number",
                max_length=34,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="extramural_ind",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                help_text="For reporting FS Research agreement activities only.",
                max_length=1,
                null=True,
                verbose_name="Extramural",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="fed_id_agency",
            field=models.CharField(
                blank=True,
                default="11",
                help_text='\n            The two-digit code the agency.\n            For the Forest Service, the agency is always "11".\n            ',
                max_length=2,
                null=True,
                verbose_name="Agency",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="fed_id_region",
            field=models.CharField(
                blank=True,
                choices=[
                    (" ", " "),
                    ("01", "01"),
                    ("02", "02"),
                    ("03", "03"),
                    ("04", "04"),
                    ("05", "05"),
                    ("06", "06"),
                    ("07", "07"),
                    ("08", "08"),
                    ("09", "09"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("15", "15"),
                    ("16", "16"),
                    ("22", "22"),
                    ("23", "23"),
                    ("24", "24"),
                    ("25", "25"),
                    ("26", "26"),
                    ("27", "27"),
                    ("33", "33"),
                    ("42", "42"),
                ],
                help_text="The two-digit code for the region of the instrument, such as 01 or 13.",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="fed_id_seq",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="The three-digit code for the sequence number of the instrument.",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="fed_id_subunit",
            field=models.CharField(
                blank=True,
                help_text="The two-digit code for the subunit.",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="fed_id_unit",
            field=models.CharField(
                blank=True,
                help_text="The two-digit code for the unit.",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="ffin",
            field=models.CharField(
                blank=True,
                help_text="The agreement number assigned to the instrument in FMMI.",
                max_length=40,
                null=True,
                verbose_name="FMMI Agreement Number",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="hhs_payment_ind",
            field=models.CharField(
                default="N",
                editable=False,
                help_text="Was only used by NRS (Northern Research Station) and NA Northeastern Area (S&PF).",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="international_act_ind",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                help_text="Indicates if the project has any associated international activities.",
                max_length=1,
                null=True,
                verbose_name="International Activities",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="master_agreement_ind",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                editable=False,
                help_text="Indicates if the instrument is a Master Agreement.",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="orig_fed_id",
            field=models.CharField(
                blank=True,
                help_text="\n            If there was a previous agreement, (prior to FY2000 numbering scheme), \n            enter the original Forest Service identification number here to supply \n            a cross-reference to the new agreement number.\n            Note: Do not enter other agency agreement numbers in this field. \n            They can be entered in the Comments field.\n        ",
                max_length=120,
                null=True,
                verbose_name="Original Agreement Number",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="progrm_responsibility_type",
            field=models.CharField(
                blank=True,
                help_text="\n            Indicates the specific responsibilities notification type \n            (Incoming Funding, Outgoing Funding, or Non-Cash ie no exchange of funding) \n            that is send to the Program Manager when the agreement is executed.\n        ",
                max_length=30,
                null=True,
                verbose_name="Program Responsibility Type",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proj_cancellation_dt",
            field=models.DateField(
                blank=True,
                help_text="The date the instrument is canceled.",
                null=True,
                verbose_name="Cancellation date",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proj_cfda_no",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10.652", "10.652 - Research and Development Forest Research"),
                    ("10.664", "10.664 - S/PF Cooperative Forestry Assistance"),
                    ("10.665", "10.665 - Schools and Roads, Payments to States"),
                    ("10.666", "10.666 - Schools and Roads, Payments to Counties"),
                    (
                        "10.670",
                        "10.670 - S/ PF National Forest Dependent Rural Communities",
                    ),
                    (
                        "10.671",
                        "10.671 - S/ PF Region 10, Southeast Alaska Economic Disaster Fund",
                    ),
                    ("10.672", "10.672 - Rural Development, Forestry and Communities"),
                    ("10.673", "10.673 - Wood in Transportation Program"),
                    ("10.674", "10.674 - Technology Marketing Unit"),
                    ("10.675", "10.675 - Urban and Community Forestry Program"),
                    ("10.676", "10.676 - Forest Legacy Program"),
                    ("10.677", "10.677 - Forest Land Enhancement Program"),
                    ("10.678", "10.678 - Forest Stewardship Program"),
                    ("10.679", "10.679 - Collaborative Forest Restoration"),
                    ("10.681", "10.681 - Wood Education and Resource Center (WERC)"),
                    ("10.682", "10.682 - National Forest Foundation"),
                    ("10.683", "10.683 - National Fish and Wildlife Foundation"),
                    ("10.684", "10.684 - International Forestry Programs"),
                    (
                        "10.685",
                        "10.685 - Recovery Act of 2009: Capital Improvement and Maintenance",
                    ),
                    (
                        "10.686",
                        "10.686 - Recovery Act of 2009: Wildland Fire Management",
                    ),
                    (
                        "10.689",
                        "10.689 - Community Forest and Open Space Conservation Program",
                    ),
                    ("10.690", "10.690 - Lake Tahoe Erosion Control Program"),
                    ("10.691", "10.691 - Good Neighbor Program"),
                    (
                        "10.692",
                        "10.692 - Secure Rural Schools and Community Self Determination Program (RAC)",
                    ),
                    (
                        "10.693",
                        "10.693 - Watershed Restoration and Enhancement (Wyden)",
                    ),
                    (
                        "10.694",
                        "10.694 - Southwest Forest Health and Wildfire Prevention",
                    ),
                ],
                help_text="\n            The Catalog of Federal Domestic Assistance (CFDA) Number. \n            Required if the instrument was issued under a federal financial assistance authority \n            (instrument type DG and CA only). REQUIRED FOR APPROVAL",
                max_length=40,
                null=True,
                verbose_name="CFDA Number",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proj_close_dt",
            field=models.DateField(
                blank=True,
                help_text="\n            The date the instrument is closed.\n            Denotes the grant or agreement has been executed and has been officially closed. \n            Required when closing the instrument\n        ",
                null=True,
                verbose_name="Close date",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proj_desc",
            field=models.TextField(
                blank=True,
                help_text="Narrative text describing the project.",
                max_length=2000,
                null=True,
                verbose_name="Project description",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proj_received_dt",
            field=models.DateField(
                blank=True,
                help_text="The date the State received the proposal for consideration.",
                null=True,
                verbose_name="Project received date",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proj_rwu",
            field=models.CharField(
                blank=True,
                choices=[
                    (" ", "None"),
                    ("FPL-4501", "Center for Forest Mycology Research"),
                    ("FPL-4502", "Biodeterioration of Wood"),
                    ("FPL-4701", "Center for Wood Anatomy Research"),
                    ("FPL-4703", "Wood Adhesives Science and Technology"),
                    ("FPL-4706", "Performance- Designed Composites"),
                    ("FPL-4707", "Wood Surface Chemistry"),
                    ("FPL-4709", "Chemistry and Pulping"),
                    ("FPL-4710", "Fiber Processing and paper Performance"),
                    ("FPL-4712", "Institute of Microbial and Biochemical Technology"),
                    ("FPL-4714", "Engineering Materials and Structures"),
                    ("FPL-4716", "Building Moisture and Durability"),
                    ("FPL-4719", "Structure Condition Assessment and Rehabilitation"),
                    ("FPL-4722", "Modified Lignocellulosic Material"),
                    ("FPL-4723", "Wood Preservation"),
                    ("FPL-4724", "Statistical Methods in Wood and Fiber Research"),
                    ("FPL-4725", "Fire Safety"),
                    ("FPL-4851", "Timber Demand and Technology Assessment Research"),
                    ("IITF-4151", "Tropical American Forest Management"),
                    (
                        "INT-4151",
                        "Ecology and Management of Northern Rocky Mountain Forest",
                    ),
                    (
                        "INT-4153",
                        "Silviculture and Genetics of Rocky Mountain Forest Ecosystems",
                    ),
                    (
                        "INT-4154",
                        "Quantitative Analysis of Forest Resource Responses for Planning, Management, and Control",
                    ),
                    ("INT-5201", "Wildlife Habitats in the Northern Rockies"),
                    ("INT-4202", "Riparian Stream Ecology and Mangement"),
                    ("INT-4203", "Enhancing Fish Habitats"),
                    ("INT-4251", "Shrubland Biology and Restoration"),
                    (
                        "INT-4252",
                        "Ecology Paleoecology and Management of Great Basin Pinyon-Juniper",
                    ),
                    ("INT-4301", "Reclamation of Disturbed Lands"),
                    (
                        "INT-4302",
                        "Watershed Disturbance and Channel Conditions in the Northern Rocky Mountains",
                    ),
                    ("INT-4401", "Fire Behavior: Fundamentals and Systems Development"),
                    ("INT-4403", "Fire Effects: Prescribed Fire and Wildfiee"),
                    ("INT-4404", "Fire Chemistry and Emission Characteristics"),
                    ("INT-4501", "Mountain Pine Beetle Population Dynamics"),
                    (
                        "INT-4551",
                        "Microbial Processes as Ecosystem Regulators in Western Forests",
                    ),
                    ("INT-4702", "Soil and Water Engineering"),
                    (
                        "INT-4801",
                        "Interior West Resource Inventory, Monitoring, and Evaluation Program",
                    ),
                    (
                        "INT-4802",
                        "Economic Aspects of Ecosystem Management on Forest Lands",
                    ),
                    ("INT-4901", "Wilderness Management Research"),
                    (
                        "NC-4108",
                        "Ecology and Culture of the Northern Lake States Forests",
                    ),
                    ("NC-4152", "Ecosystem Processes"),
                    (
                        "NC-4153",
                        "Physiological Mechanisms of Growth, Multiple-Stress Responses in Northern Forest Trees",
                    ),
                    (
                        "NC-4154",
                        "Principles of Landscape Ecology for Managing Temperate Ecosystems",
                    ),
                    (
                        "NC-4155",
                        "Silviculture and Ecology of Upland Central Hardwood Forests",
                    ),
                    (
                        " ",
                        "Genetic and Molecular Base of Forest Tree Stress Tolerances",
                    ),
                    ("NC-4157", "Hardwood Tree Improvement & Regeneration"),
                    (
                        "NC-4158",
                        "Genetic & Silvicultural Systems for Sustainable Intensive Forestry",
                    ),
                    ("NC-4159", "Ecosystem Processes"),
                    (
                        "NC-4351",
                        "Ecology and Management of Riparian/ Aquatic Ecosystems",
                    ),
                    (
                        "NC-4401",
                        "Atmospheric and Socioeconomic Relationships with Wildland Fire",
                    ),
                    ("NC-4455", "Global Change"),
                    (
                        "NC-4501",
                        "Stress Effects on Tree-Insect-Natural Enemy interaction",
                    ),
                    (
                        "NC-4502",
                        "Rapid Systems for Disease Resistance and Control of Diseases in Nurseries, Forests, Plantations, and Christmas Tree Plantings",
                    ),
                    (
                        "NC-4509",
                        "Genetics and Management of Invasive Forest Insect Pests, Diseases, and Beneficial Fungi",
                    ),
                    (
                        "NC-4702",
                        "Engineering Technology for Managing Forest Ecosystems",
                    ),
                    (
                        "NC-4801",
                        "Forest Inventory and Analysis for the North Central and Northern Great Plains State",
                    ),
                    (
                        "NC-4803",
                        "Social and Economic Dimensions of Ecosystem Management",
                    ),
                    (
                        "NC-4804",
                        "Economics of Alternate Forest Management Choices in the North",
                    ),
                    ("NC-4902", "Managing Forest Environments for Urban Populations"),
                    (
                        "NE-4103",
                        "The Role of Environmental Stress on Tree Growth and Development",
                    ),
                    (
                        "NE-4104",
                        "Forest Carbon Dynamics and Estimation for Sustainable Management",
                    ),
                    (
                        "NE-4152",
                        "Research to Develop Guidelines and Indicators for Sustaining Forest Ecosystems of Pennsylvania and the Adjacent Allegheny Plateau Region",
                    ),
                    (
                        "NE-4153",
                        "Quantitate Methods for Modeling and Monitoring Response of Northeastern Forest Ecosystems to Management and Environmental Stresses",
                    ),
                    ("NE-4155", "Ecology and Management of Northern Forest Ecosystems"),
                    (
                        "NE-4251",
                        "Wildlife and Fish Habitat Relationships and Recreation in New England Forests",
                    ),
                    (
                        "NE-4252",
                        "Atlantic Salmon Habitat Restoration, Ecology and Management",
                    ),
                    (
                        "NE-4352",
                        "Ecological Process: A Basic for Managing Forest and Protecting Water in New England",
                    ),
                    (
                        "NE-4353",
                        "Sustaining the Diversity and Productivity of Appalachian Forests",
                    ),
                    (
                        "NE-4454",
                        "Integrating Social and Biophysical Sciences for Natural Resource Management",
                    ),
                    ("NE-4455", "Northern Global Changes Research Program"),
                    (
                        "NE-450",
                        "Development of Biologically Based Controls for Forest Insect Pests and Diseases through Molecular Technologies",
                    ),
                    ("NE-4501", "Forest Insect Biology and Biocontrol"),
                    (
                        "NE-4502",
                        "Pathology and Microbial Control of Insects that Impact the Health of Eastern Forest Trees",
                    ),
                    (
                        "NE-4505",
                        "Forest Sustainability and Tress Response to Injury, Infection, and Environmental Change",
                    ),
                    (
                        "NE-4557",
                        "Disturbance Ecology and Management of Oak Dominated Forest",
                    ),
                    (
                        "NE-4558",
                        "Multiple Stress Interactions and their Effects on Forest Health and Sustainability",
                    ),
                    ("NE-4701", "Efficient Use of the Northern Forest Resource"),
                    (
                        "NE-4751",
                        "Integration of Forest Operations into Eastern Hardwood Intermediate Cuttings and Structural Retention Treatments",
                    ),
                    ("NE-4801", "Forest Inventory and Analysis"),
                    ("NE-4803", "Eastern Forest Use in a Global Economy"),
                    (
                        "NE-4805",
                        "The influence of Markets on Sustainability of Eastern Hardwood Forests",
                    ),
                    (
                        "NE-4952",
                        "Effects of Urban Forests and their Management on Human Health and Environmental Quality",
                    ),
                    (
                        "RM-4151",
                        "Research on Sustainable Multi-Resource Management of Forest and Woodland Ecological Systems in Central and Rocky Mountain",
                    ),
                    (
                        "RM-4152",
                        "Ecological Roles of Insects and Pathogens in Coniferous Forests of the Interior West",
                    ),
                    (
                        "RM-4201",
                        "Wildlife Habitat Relationship in Central Rocky Mountains",
                    ),
                    (
                        "RM-4251",
                        "Sustainability of Southwestern Forest and Woodland Terrestrial Ecological Systems",
                    ),
                    (
                        "RM-4252",
                        "Management for Sustainable Ecological Systems of the Northern and Central Great Plains",
                    ),
                    (
                        "RM-4301",
                        "Research on Sustaining Fish and Watershed Components of Aquatic and Riparian Ecological Systems in Central and Southern Rocky Mountain",
                    ),
                    (
                        "RM-4302",
                        "Sustainability of Riparian Ecological Systems in Southwestern Forests and Woodlands",
                    ),
                    (
                        "RM-4351",
                        "Ecology, Recovery, and Sustainability of Southwestern Grassland and Associated Riparian Ecosystems and Wildlife",
                    ),
                    (
                        "RM-4352",
                        "Research on Sustaining Fish and Watershed Components of Aquatic and Riparian Ecosystems in the Central Rocky Mountains and Northern Great Plains",
                    ),
                    (
                        "RM-4451",
                        "Sustaining Alpine and Forest Ecosystems under Atmospheric and Terrestrial Disturbances",
                    ),
                    (
                        "RM-4452",
                        "Effects of Atmospheric Change on Alphine and Subalpine Ecosystems",
                    ),
                    (
                        "RM-4551",
                        "Improvement of Stress-Pest Resistance of Great Plains Tree Species",
                    ),
                    (
                        "RM-4651",
                        "Ecological Basic for Research of Borderlands of Southern U.S.",
                    ),
                    (
                        "RM-4652",
                        "Ecology, Diversity, and Sustainability of Soil, Plant, Animal and Human Resources of the Rio Grande Basin",
                    ),
                    (
                        "RM-4653",
                        "Research on Sustaining Social, Biological, and Physical Components of CO Front Range Ecosystems",
                    ),
                    ("RM-4802", "Multi- Resource Inventory Techniques"),
                    (
                        "RM-4803",
                        "Advanced Research in Economics and Optimization for Forest Service Planning",
                    ),
                    (
                        "RM-4851",
                        "Identification and Valuation of Wildland Resource Benefits",
                    ),
                    (
                        "RM-4852",
                        "Natural Resource Assessment Ecology and Management Science Research",
                    ),
                    ("RM-4853", "Cultural Heritage Research"),
                    (
                        "RMRS-4151",
                        "Ecology and Management of Northern Rocky Mountain Forests",
                    ),
                    (
                        "RMRS-4152",
                        "Ecological Roles of Insects and Pathogens in Coniferous Forests of the Interior West",
                    ),
                    (
                        "RMRS-4155",
                        "Effects of Environmental Variability and Forest Management on Ecosystem Processes that Regulate Forest Dynamics in the Interior West",
                    ),
                    (
                        "RMRS-4156",
                        "South Western Wildland-Urban Interface Fuels Management and Forest Health Restoration",
                    ),
                    ("RMRS-4201", "Wildlife Ecology in Rocky Mountain Landscapes"),
                    (
                        "RMRS-4251",
                        "Ecology and Conservation of Terrestrial Wildlife and Habitats of the Interior West",
                    ),
                    (
                        "RMRS-4252",
                        "Ecology, Paleoecology, and Restoration of Great Basin Watersheds",
                    ),
                    (
                        "RMRS-4254",
                        "Management of Sustainable Ecological Systems of Northern and Central Great Plains",
                    ),
                    ("RMRS-4301", "Restoration of Disturbed Ecosystems"),
                    (
                        "RMRS-4302",
                        "Watersheds and Riparian Ecosystems of Forests and Woodlands in the Semi-Arid West",
                    ),
                    (
                        "RMRS-4351",
                        "Ecology, Recovery, and Sustainability of Southwestern Grassland and Associated Riparian Ecosystems and Wildlife",
                    ),
                    (
                        "RMRS-4352",
                        "Sustaining Fish and Watershed Components of Aquatic and Riparian Ecological Systems in Central Rocky Mountains and Northern Great Plains",
                    ),
                    ("RMRS-4353", "Shrubland Biology and Restoration"),
                    ("RMRS-4401", "Fire Behavior Fundamentals and Systems Development"),
                    ("RMRS-4403", "Fire Effects: Prescribed Fire and Wildfire"),
                    ("RMRS-4404", "Fire Chemistry"),
                    (
                        "RMRS-4451",
                        "Sustaining Alpine and Forest Ecosystems under Atmospheric and Terrestrial Disturbances",
                    ),
                    (
                        "RMRS-4501",
                        "Disturbances Ecology in the Interior West: Bark Beetle Disturbance in Conifer Forests",
                    ),
                    (
                        "RMRS-4551",
                        "Tree- Based Buffer Technologies for Sustainable Land Use in the Central U.S.",
                    ),
                    (
                        "RMRS-4552",
                        "Microbial Processes as Ecosystem Regulators in Western Forests",
                    ),
                    ("RMRS-4651", "Southwestern Borderlands Ecosystem Mangement"),
                    (
                        "RMRS-4652",
                        "Ecology, Diversity, and Sustainability of Soil, Plant, Animal and Human Resources of the Rio Grande Basin",
                    ),
                    (
                        "RMRS-4653",
                        "Sustaining Social, Biological, and Physcial Components of Colorado Front Range Ecosystems Management Project",
                    ),
                    ("RMRS-4654", "Bitterroot Ecosystem Management Research Proejct"),
                    ("RMRS-4655", "Interdisciplinary Ecosystem Management Project"),
                    ("RMRS-4702", "Soil and Water Engineering"),
                    (
                        "RMRS-4801",
                        "Interior West Resource Inventory, Monitoring, and Evaluation Program",
                    ),
                    (
                        "RMRS-4802",
                        "Economic Aspects of Forest Management on Public Lands",
                    ),
                    ("RMRS-4804", "Forest Inventory and Monitoring Environmetrics"),
                    (
                        "RMRS-4851",
                        "Identification and Valuation of Wildland Resource Benefits",
                    ),
                    (
                        "RMRS-4852",
                        "Natural Resource Assessment Ecology and Management Science",
                    ),
                    ("RMRS-4853", "Cultural Heritage Research"),
                    ("RMRS-4901", "Wilderness Management Research"),
                    ("PNW-64", "Administration"),
                    ("PNW-4163", "Resource Management and Productivity"),
                    ("PNW-4166", "Focus Science Delivery"),
                    ("PNW-4261", "Aquatic and Land Interaction Research Programs"),
                    ("PNW-4362", "Ecosystem Processes"),
                    (
                        "PNW-4577",
                        "Managing Natural Disturbance to Sustain Forest Health",
                    ),
                    ("PNW-4865", "Social and Economic Values Research Programs"),
                    (
                        "PNW-4869",
                        "Pacific Resource Inventory Monitoring and Evaluation Research, Development and Application Program",
                    ),
                    ("PNW-4103", "People and Natural Resources"),
                    (
                        "PSW-4154",
                        "National Forest Genetic Electrophoresis Laboratory (Placerville, CA)",
                    ),
                    ("PSW-4155", "Institute of Pacific Islands Forestry"),
                    (
                        "PSW-4202",
                        "Ecology and Management of Western Forests Influences by Mediterranean Climate",
                    ),
                    ("PSW-4251", "Forestry Sciences Laboratory (Fresno, CA)"),
                    (
                        "PSW-4351",
                        "Wildlife Habitats in Mature and Old Growth Forests of Northern California",
                    ),
                    (
                        "PSW-4401",
                        "Cumulative Effects of Forest Management on Hillslope Processes, Fishery Resources and Downstream Environments",
                    ),
                    ("PSW-4402", "Fire Meteorology"),
                    (
                        "PSW-4403",
                        "Wildland Fire Management Research, Development, and Application",
                    ),
                    ("PSW-4451", "Prescribed Fire and Fire Effects"),
                    (
                        "PSW-4502",
                        "Atmospheric Deposition Effects on Western Forest Ecosystems",
                    ),
                    ("PSW-4651", "Chemical Ecology of Forest Insects"),
                    (" ", "Pacific Northwest Forest Plan"),
                    ("PSW-4902", "Wildland Recreation and Urban Cultures"),
                    ("PSW-4952", "Center for Urban Forest Research"),
                    (
                        "SRS-4101",
                        "Ecology and Management of Southern Appalachian Hardwoods",
                    ),
                    ("SRS-4103", "Center for Forested Wetlands Research"),
                    (
                        "SRS-4104",
                        "Disturbance and Management of Southern Pine Ecosystem",
                    ),
                    (
                        "SRS-4105",
                        "Integrated Vegetation Management for Sustaining Southern Forests and Longleaf Pine Ecosystems",
                    ),
                    ("SRS-4106", "Managing Upland Forest Ecosystems in the Midsouth"),
                    (
                        "SRS-4111",
                        "Ecology and Management of Even-Aged Southern Pine Forest",
                    ),
                    ("SRS-4153", "Southern Institute of Forest Genetics"),
                    (
                        "SRS-4154",
                        "Biological Foundations of Southern Forest Productivity and Sustainability",
                    ),
                    ("SRS-4155", "Center for Bottomland Hardwoods Research"),
                    (
                        "SRS-420",
                        "Coldwater Streams and Trout Habitat in the Southern Appalachians",
                    ),
                    (
                        "SRS-4201",
                        "Endangered, Threatened and Sensitive Wildlife and Plants in Southern Forests",
                    ),
                    (
                        "SRS-4202",
                        "Coldwater Streams and Trout Habitat in the Southern Appalachians",
                    ),
                    (
                        "SRS-4251",
                        "Integrated Management of Wildlife Habitat and Timber Resources",
                    ),
                    (
                        "SRS-4351",
                        "Evaluation of Watershed Ecosystem Responses to Natural, Management, and other Human Disturbances of Southern Forests",
                    ),
                    ("SRS-4501", "Bark Beetles and Invasive Insects"),
                    ("SRS-4502", "Wood Products Insect Research"),
                    ("SRS-4505", "Insects and Diseases of Southern Forests"),
                    ("SRS-4701", "Utilization of Southern Forest Resources"),
                    ("SRS-4702", "Forest Products Conservation"),
                    (
                        "SRS-4703",
                        "Forest Operations Research to Achieve Sustainable Management",
                    ),
                    ("SRS-4801", "Forest Inventory and Analysis"),
                    (
                        "SRS-4802",
                        "Evaluation of Legal, Tax, and Economic Influences on Forest Resource Management",
                    ),
                    ("SRS-4803", "Forest Health Monitoring"),
                    ("SRS-4851", "Economics of Forest Protection and Management"),
                    ("SRS-4852", "Southern Global Change Program"),
                    (
                        "SRS-4901",
                        "Recreation, Wilderness, Urban Forest and Demographic Trends Research",
                    ),
                    (
                        "SRS-4901",
                        "Assessing Trends, Values and Rural Community Benefits from Outdoor Recreation and Wilderness in Forest Ecosystems",
                    ),
                ],
                max_length=10,
                null=True,
                verbose_name="Research Work Unit",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proj_science_cd",
            field=models.CharField(
                blank=True,
                choices=[
                    ("12", "Chemistry"),
                    ("21", "Mathematics"),
                    ("22", "Computer Sciences"),
                    ("31", "Atmospheric Sciences"),
                    ("32", "Earth Science"),
                    ("43", "Chemical"),
                    ("49", "Engineering, n.o.c."),
                    ("51", "Biological"),
                    ("54", "Environmental Biology"),
                    ("55", "Agricultural Sciences"),
                    ("71", "Anthropology"),
                    ("72", "Economics"),
                    ("76", "Sociology"),
                    ("79", "Social Sciences"),
                ],
                max_length=3,
                null=True,
                verbose_name="Science Code",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proj_status",
            field=models.CharField(
                blank=True,
                choices=[("", "----"), ("01", "01"), ("02", "02")],
                help_text="The Status of the grant or agreement (instrument).",
                max_length=15,
                null=True,
                verbose_name="Project status",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proj_title",
            field=models.CharField(
                db_index=True,
                help_text="The short and concise name of the project.",
                max_length=200,
                verbose_name="Project title",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proposed_end_date",
            field=models.DateField(
                help_text="The date the project is expected to end as negotiated in the agreement."
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="proposed_start_date",
            field=models.DateField(
                help_text="\n            The date the project is expected to start as negotiated in the agreement.\n            This date cannot be after the Expiration date.\n        "
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="research_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Applied"),
                    ("B", "Basic"),
                    ("D", "Developmental"),
                    ("N", "None"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="state_eo_code",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                help_text="Is this instrument subject to Executive Order 12372 review?",
                max_length=1,
                null=True,
                verbose_name="Subject to State E.O.",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="state_eo_date",
            field=models.DateField(
                blank=True,
                help_text="\n            Executive Order 12372 review date. \n            You must select a data if you selected Yes for Subject to State E.O.",
                null=True,
                verbose_name="EO Date",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="status",
            field=models.CharField(
                choices=[
                    ("AGREEMENT-ACTION", "Agreement action"),
                    ("NEW-APPLICATION", "New application"),
                    ("APP-ACCEPTED", "App accepted"),
                    ("APP-APPROVED", "App approved"),
                    ("APP-PGM REJECTED", "App PGM rejected"),
                    ("APP-RECEIVED", "App received"),
                    ("APP-REJECTED", "App rejected"),
                    ("GA-CANCELLED", "GA closed"),
                    ("GA-EXECUTED", "GA executed"),
                    ("GA-PENDING", "GA pending"),
                    ("GA-TERMINATED", "GA terminated"),
                ],
                max_length=40,
                verbose_name="Agreement Status",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="wppp_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Awaiting Documentation", "Awaiting Documentation"),
                    ("Executed- Active", "Executed - Active"),
                    ("G&A Closed", "G&A Closed"),
                    ("G&A Closeout in process", "G&A Closeout in process"),
                    ("G&A Reviewing", "G&A Reviewing"),
                    ("New", "New"),
                    ("Out for Signature", "Out for Signature"),
                    ("Pending ASC Action", "Pending ASC Action"),
                ],
                max_length=40,
                null=True,
                verbose_name="WPAP Status",
            ),
        ),
        migrations.AlterField(
            model_name="grantauthority",
            name="authority_cd",
            field=models.CharField(
                help_text="\n            The legislative authority code under which the instrument was authorized. \n            The full list is in the GA User Guide",
                max_length=40,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="grantauthority",
            name="grant",
            field=models.ForeignKey(
                db_column="grant_cn",
                editable=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="grants.grant",
            ),
        ),
        migrations.AlterField(
            model_name="grantauthority",
            name="last_update",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="cn",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=34,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="comments",
            field=models.CharField(
                help_text="Any additional comments regarding the project.",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="created_by",
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name="note",
            name="created_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="created_in_instance",
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name="note",
            name="email_date",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="The date the note was sent to the e-mail recipient(s).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="email_to",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The e-mail address(es) of the note recipient (if the message was sent to via e-mail).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="last_update",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="modified_by",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="modified_date",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="modified_in_instance",
            field=models.DecimalField(
                blank=True, decimal_places=0, editable=False, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="note_by",
            field=models.CharField(
                editable=False,
                help_text="The user ID of the person who created the note.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="note_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="note_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGREEMENT", "Agreement"),
                    ("COMMITMENT", "Commitment"),
                    ("OBLIGATION", "Obligation"),
                    ("PAYMENT", "Payment"),
                    ("MODIFICATION", "Modification"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
