# Generated by Django 3.1.7 on 2021-03-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0008_auto_20210324_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='aop_ind',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', help_text='\n            Select Yes from the choice list if the instrument requires an Annual Operating Plan (AOP).\n        ', max_length=1, null=True, verbose_name='AOP'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='app_submission_type',
            field=models.CharField(choices=[('NEW', 'New'), ('Application', 'Application'), ('Preapplication', 'Pre-application'), ('NON-CONSTRUCTION PRE-APPLICATION', 'Non-construction Pre-application'), ('NON-CONSTRUCTION APPLICATION', 'Non-construction Application'), ('CONSTRUCTION PRE-APPLICATION', 'Construction Pre-application'), ('CONSTRUCTION APPLICATION', 'Construction Application'), ('MOU', 'Mou'), ('OTHER', 'Other'), ('8/1/2004NON-CONSTRUCTION APPLICATION', '8/1/2004NON-CONSTRUCTION APPLICATION'), ('5/1/2005NON-CONSTRUCTION APPLICATION', '5/1/2005NON-CONSTRUCTION APPLICATION')], help_text='\n            Applies to instruments with Federal Financial Assistance (FFA).\n            Select OTHER if not FFA.\n        ', max_length=100, verbose_name='Type of Submission'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='application_type',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTINUATION', 'Continuation'), ('REVISION A-INCREASE AWARD', 'Revision A - Increase Award'), ('REVISION B-DECREASE AWARD', 'Revision B - Decrease Award'), ('REVISION C-INCREASE AWARD', 'Revision C - Increase Duration'), ('REVISION D-DECREASE AWARD', 'Revision D - Decrease Duration'), ('OTHER', 'Other')], help_text='\n            Applies to instruments with Federal Financial Assistance (FFA).\n            Select OTHER if not FFA.\n        ', max_length=30, verbose_name='Type of application'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='orig_fed_id',
            field=models.CharField(blank=True, help_text='\n            If there was a previous agreement, (prior to FY2000 numbering scheme),\n            enter the original Forest Service identification number here to supply\n            a cross-reference to the new agreement number.\n            Note: Do not enter other agency agreement numbers in this field.\n            They can be entered in the Comments field.\n        ', max_length=120, null=True, verbose_name='Original Agreement Number'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='progrm_responsibility_type',
            field=models.CharField(blank=True, help_text='\n            Indicates the specific responsibilities notification type\n            (Incoming Funding, Outgoing Funding, or Non-Cash ie no exchange of funding)\n            that is send to the Program Manager when the agreement is executed.\n        ', max_length=30, null=True, verbose_name='Program Responsibility Type'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='proj_cfda_no',
            field=models.CharField(blank=True, choices=[('10.652', '10.652 - Research and Development Forest Research'), ('10.664', '10.664 - S/PF Cooperative Forestry Assistance'), ('10.665', '10.665 - Schools and Roads, Payments to States'), ('10.666', '10.666 - Schools and Roads, Payments to Counties'), ('10.670', '10.670 - S/ PF National Forest Dependent Rural Communities'), ('10.671', '10.671 - S/ PF Region 10, Southeast Alaska Economic Disaster Fund'), ('10.672', '10.672 - Rural Development, Forestry and Communities'), ('10.673', '10.673 - Wood in Transportation Program'), ('10.674', '10.674 - Technology Marketing Unit'), ('10.675', '10.675 - Urban and Community Forestry Program'), ('10.676', '10.676 - Forest Legacy Program'), ('10.677', '10.677 - Forest Land Enhancement Program'), ('10.678', '10.678 - Forest Stewardship Program'), ('10.679', '10.679 - Collaborative Forest Restoration'), ('10.681', '10.681 - Wood Education and Resource Center (WERC)'), ('10.682', '10.682 - National Forest Foundation'), ('10.683', '10.683 - National Fish and Wildlife Foundation'), ('10.684', '10.684 - International Forestry Programs'), ('10.685', '10.685 - Recovery Act of 2009: Capital Improvement and Maintenance'), ('10.686', '10.686 - Recovery Act of 2009: Wildland Fire Management'), ('10.689', '10.689 - Community Forest and Open Space Conservation Program'), ('10.690', '10.690 - Lake Tahoe Erosion Control Program'), ('10.691', '10.691 - Good Neighbor Program'), ('10.692', '10.692 - Secure Rural Schools and Community Self Determination Program (RAC)'), ('10.693', '10.693 - Watershed Restoration and Enhancement (Wyden)'), ('10.694', '10.694 - Southwest Forest Health and Wildfire Prevention')], help_text='\n            The Catalog of Federal Domestic Assistance (CFDA) Number.\n            Required if the instrument was issued under a federal financial assistance authority\n            (instrument type DG and CA only). REQUIRED FOR APPROVAL', max_length=40, null=True, verbose_name='CFDA Number'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='proj_close_dt',
            field=models.DateField(blank=True, help_text='\n            The date the instrument is closed.\n            Denotes the grant or agreement has been executed and has been officially closed.\n            Required when closing the instrument.\n        ', null=True, verbose_name='Close date'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='state_eo_date',
            field=models.DateField(blank=True, help_text='\n            Executive Order 12372 review date.\n            You must select a data if you selected Yes for Subject to State E.O.', null=True, verbose_name='EO Date'),
        ),
        migrations.AlterField(
            model_name='grantauthority',
            name='authority_cd',
            field=models.CharField(help_text='\n            The legislative authority code under which the instrument was authorized.\n            The full list is in the GA User Guide', max_length=40, verbose_name='Code'),
        ),
    ]
