CREATE TABLE ACCPLISHMENT_INSTRUMENTS
(
   CN                       VARCHAR(34)     NOT NULL PRIMARY KEY,
   ID                       VARCHAR(40)     NOT NULL,
   NAME                     VARCHAR(200),
   OBJ_TECH                 VARCHAR(30)     DEFAULT 'ORACLE' NOT NULL,
   OBJ_NAME                 VARCHAR(30)     NOT NULL,
   OBJ_CLASS                VARCHAR(30)     DEFAULT 'ACCOMPLISHMENT_INSTRUMENT' NOT NULL,
   MANAGING_CONT_CN         VARCHAR(34),
   REPLACED_BY_AI_CN        VARCHAR(34),
   DESCRIPTION              VARCHAR(4000),
   EXP_EXPIRATION_DATE      DATE,
   TIM_ALLOW_UPDATES        VARCHAR(1),
   TIM_CONTRACT_NO          VARCHAR(15),
   TIM_REGION               VARCHAR(2),
   TIM_FOREST               VARCHAR(2),
   TIM_DISTRICT             VARCHAR(2),
   ACBLADD_BILL_ADDRESS_ID  NUMERIC(10),
   TRANS_ID                 VARCHAR(34),
   CREATED_BY               VARCHAR(30)     NOT NULL,
   CREATED_DATE             DATE                  NOT NULL,
   CREATED_IN_INSTANCE      NUMERIC(6)             NOT NULL,
   MODIFIED_BY              VARCHAR(30),
   MODIFIED_DATE            DATE,
   MODIFIED_IN_INSTANCE     NUMERIC(6),
   MASTER_SITE              NUMERIC(6),
   SECURITY_ID              VARCHAR(30)     NOT NULL,
   AGENCY_CODE              VARCHAR(4)      DEFAULT '11',
   PARENT_CN                VARCHAR(34),
   CHECK (  tim_allow_updates IN ( 'N' , 'Y' )   ),
   CHECK (  tim_allow_updates IN ( 'N' , 'Y' )   ),
   CONSTRAINT AI_NAME_UPPER_CHK CHECK (        NAME=UPPER(NAME)        ),
   CONSTRAINT AI_ID_UPPER_CHK CHECK (        ID = UPPER(ID)        )
);

CREATE INDEX II_CN_SECID_OBJN_IDX
   ON ACCPLISHMENT_INSTRUMENTS (CN ASC, SECURITY_ID ASC, OBJ_NAME ASC, MANAGING_CONT_CN ASC, NAME ASC, ID ASC)
   ;

CREATE INDEX II_ACCINST_IDX
   ON ACCPLISHMENT_INSTRUMENTS (MANAGING_CONT_CN ASC, SECURITY_ID ASC, CN ASC)
   ;

ALTER TABLE ACCPLISHMENT_INSTRUMENTS
   ADD CONSTRAINT ACCINST_ACCINST2_UK UNIQUE (OBJ_NAME, ID, SECURITY_ID, TRANS_ID);

CREATE INDEX ACCINST_ACBLADD_FK_I
   ON ACCPLISHMENT_INSTRUMENTS (ACBLADD_BILL_ADDRESS_ID ASC)
   ;

CREATE INDEX ACCINST_CONT_FK_I
   ON ACCPLISHMENT_INSTRUMENTS (MANAGING_CONT_CN ASC)
   ;

CREATE INDEX ACCINST_OBJ_FK_I
   ON ACCPLISHMENT_INSTRUMENTS (OBJ_TECH ASC, OBJ_NAME ASC, OBJ_CLASS ASC)
   ;

CREATE INDEX ACCINST_SECURITY_ID_I
   ON ACCPLISHMENT_INSTRUMENTS (SECURITY_ID ASC)
   ;

CREATE INDEX ACCINST_TRANS_FK_I
   ON ACCPLISHMENT_INSTRUMENTS (TRANS_ID ASC)
   ;

CREATE INDEX ACCINST_REPLACED_BY_FK_I
   ON ACCPLISHMENT_INSTRUMENTS (REPLACED_BY_AI_CN ASC)
   ;

CREATE INDEX ACCINST_LMG_I
   ON ACCPLISHMENT_INSTRUMENTS (OBJ_NAME ASC, MANAGING_CONT_CN ASC, CN ASC, ID ASC, SECURITY_ID ASC)
   ;

CREATE INDEX ACCINST_OBJ_SECID
   ON ACCPLISHMENT_INSTRUMENTS (OBJ_NAME ASC, SECURITY_ID ASC)
   ;
