CREATE TABLE II_GRANTS
(
   CN                              VARCHAR(34)     NOT NULL,
   PROJ_TITLE                      VARCHAR(200)    NOT NULL,
   PROJ_STATUS                     VARCHAR(15),
   APPLICATION_ID                  VARCHAR(34)     NOT NULL,
   APPLICATION_TYPE                VARCHAR(30)     NOT NULL,
   APP_SUBMISSION_TYPE             VARCHAR(100)    NOT NULL,
   APP_SUBMIT_DATE                 DATE             NOT NULL,
   APP_RECEIVED_DATE               DATE             NOT NULL,
   HHS_PAYMENT_IND                 VARCHAR(1)      NOT NULL,
   PROPOSED_START_DATE             DATE             NOT NULL,
   PROPOSED_END_DATE               DATE             NOT NULL,
   LOCKED_IND                      VARCHAR(1)      NOT NULL,
   STATUS                          VARCHAR(40)     NOT NULL,
   STATUS_DATE                     DATE             NOT NULL,
   CREATED_BY                      VARCHAR(30)     NOT NULL,
   CREATED_DATE                    DATE             NOT NULL,
   CREATED_IN_INSTANCE             NUMERIC(6)        NOT NULL,
   MODIFIED_BY                     VARCHAR(30),
   MODIFIED_DATE                   DATE,
   MODIFIED_IN_INSTANCE            NUMERIC(6),
   FED_ID_FY                       VARCHAR(4),
   FED_ID_TYPE                     VARCHAR(2),
   FED_ID_AGENCY                   VARCHAR(2),
   FED_ID_REGION                   VARCHAR(2),
   FED_ID_UNIT                     VARCHAR(2),
   FED_ID_SUBUNIT                  VARCHAR(2),
   FED_ID_SEQ                      NUMERIC(3),
   PROJ_DESC                       VARCHAR(2000),
   PROJ_RECEIVED_DT                DATE,
   PROJ_EXECUTION_DT               DATE,
   PROJ_START_DT                   DATE,
   PROJ_OBLIGATION_DT              DATE,
   PROJ_EXPIRATION_DT              DATE,
   PROJ_RWU                        VARCHAR(10),
   PROJ_CLOSE_DT                   DATE,
   PROJ_CANCELLATION_DT            DATE,
   DATE_MAILED                     DATE,
   DATE_SIGNED                     DATE,
   EXTRAMURAL_IND                  VARCHAR(1),
   PROJ_CFDA_NO                    VARCHAR(40),
   PROJ_SCIENCE_CD                 VARCHAR(3),
   RESEARCH_TYPE                   VARCHAR(1),
   JOURNAL_IND                     VARCHAR(1),
   MOD_NUMBER                      NUMERIC(3),
   ORIG_FED_ID                     VARCHAR(120),
   COMMENTS                        VARCHAR(2000),
   MASTER_FED_ID                   VARCHAR(120),
   AOP_IND                         VARCHAR(1),
   GEO_TYPE                        VARCHAR(2),
   MANAGING_STATE_COUNTY           VARCHAR(240),
   AREAS_EFFECTED                  VARCHAR(200),
   FFIN                            VARCHAR(40),
   STATE_IDENTIFIER                VARCHAR(40),
   STATE_EO_CODE                   VARCHAR(1),
   STATE_EO_DATE                   DATE,
   FED_EST_FUND                    NUMERIC(12,2),
   APPLICANT_EST_FUND              NUMERIC(12,2),
   STATE_EST_FUND                  NUMERIC(12,2),
   LOCAL_EST_FUND                  NUMERIC(12,2),
   PI_EST_FUND                     NUMERIC(12,2),
   OTH_EST_FUND                    NUMERIC(12,2),
   REROUTE_FROM                    VARCHAR(10),
   REROUTE_DATE                    DATE,
   PROJECT_CONGRESSIONAL_DISTRICT  VARCHAR(40),
   CERTIFICAION_DATE               DATE,
   FFIS_DOC_ID                     VARCHAR(11),
   APPLICANT_NAME                  VARCHAR(200),
   INTERNATIONAL_ACT_IND           VARCHAR(1),
   PROJ_TYPE                       VARCHAR(3),
   ADVANCE_ALLOWED_IND             VARCHAR(1),
   AUTHORITY_APPROVAL              VARCHAR(1),
   AUTHORITY                       VARCHAR(1),
   FORMAT                          VARCHAR(1),
   OTHER_APPROVAL                  VARCHAR(1),
   MASTER_AGREEMENT_IND            VARCHAR(1),
   PROGRM_RESPONSIBILITY_TYPE      VARCHAR(30),
   WPPP_STATUS                     VARCHAR(40),
   WPPP_STATUS_DATE                DATE,
   COOPERATOR_AGREEMENT_NUMBER     VARCHAR(34),
   GID                             VARCHAR(16),
   ADMIN_OPEN                      VARCHAR(1),
   LAST_UPDATE                     DATE             NOT NULL
);
