CREATE TABLE II_ACCINST_CONT_LINKS
(
   ACCINST_CN                   VARCHAR(34)    NOT NULL,
   CONT_CN                      VARCHAR(34)    NOT NULL,
   LINK_TYPE_NAME               VARCHAR(40)    NOT NULL,
   START_DATE                   DATE,
   END_DATE                     DATE,
   REMARKS                      VARCHAR(255),
   LEADING_IND                  VARCHAR(1),
   DEPARTMENT                   VARCHAR(40),
   DIVISION                     VARCHAR(40),
   FFIS_VENDOR_ID_PRE_FMMI      VARCHAR(11),
   FAADS_ADDR_CN                VARCHAR(34),
   INSTITUTION_CODE             VARCHAR(40),
   FED_DEBT_DELNQNT_IND         VARCHAR(1),
   PAYEE_IND                    VARCHAR(1),
   APPLICANT_IND                VARCHAR(1),
   LINK_SUB_TYPE                VARCHAR(40),
   CN                           VARCHAR(34)    NOT NULL PRIMARY KEY,
   FFIS_CAN_NUMBER_STATUS       VARCHAR(40),
   PAYER_IND                    VARCHAR(1),
   FMMI_CUSTOMER_NUMBER         VARCHAR(10),
   FFIS_VENDOR_ID               VARCHAR(10),
   FMMI_CUSTOMER_NUMBER_STATUS  VARCHAR(40),
   SAM_EXPIRATION_DATE          DATE
)
;

CREATE INDEX ACCINST_CL_ACCINST_FK_I
   ON II_ACCINST_CONT_LINKS (ACCINST_CN ASC)
   ;

CREATE INDEX ACCINST_CL_LINK_SUB_TYPE_I
   ON II_ACCINST_CONT_LINKS (LINK_SUB_TYPE ASC)
   ;

CREATE INDEX ACCINST_CL_FAADS_FK1_IDX
   ON II_ACCINST_CONT_LINKS (FAADS_ADDR_CN ASC)
   ;

CREATE INDEX ACCINST_CL_VEND_FK2_IDX
   ON II_ACCINST_CONT_LINKS (FFIS_VENDOR_ID_PRE_FMMI ASC)
   ;

CREATE INDEX II_ACC_LINKS_IDX
   ON II_ACCINST_CONT_LINKS (LINK_TYPE_NAME ASC, ACCINST_CN ASC, FFIS_VENDOR_ID ASC, PAYEE_IND ASC)
   ;

CREATE INDEX ACCINST_CL_VEND_FK3_IDX
   ON II_ACCINST_CONT_LINKS (FFIS_VENDOR_ID ASC)
   ;

CREATE INDEX ACCINST_CL_LINK_TYPE_NAME_I
   ON II_ACCINST_CONT_LINKS (LINK_TYPE_NAME ASC)
   ;

ALTER TABLE II_ACCINST_CONT_LINKS
   ADD CONSTRAINT ACCINST_CL_UK UNIQUE (ACCINST_CN, CONT_CN, LINK_TYPE_NAME, LINK_SUB_TYPE);

CREATE INDEX ACCINST_CL_PAYEE_IND_I
   ON II_ACCINST_CONT_LINKS (PAYEE_IND ASC)
   ;

CREATE INDEX ACCINST_CL_CONT_FK_I
   ON II_ACCINST_CONT_LINKS (CONT_CN ASC)
   ;

CREATE INDEX ACCINST_CL_APPLICANT_IND_I
   ON II_ACCINST_CONT_LINKS (APPLICANT_IND ASC)
   ;

CREATE INDEX ACCINST_CL_LEADING_IND_I
   ON II_ACCINST_CONT_LINKS (LEADING_IND ASC)
   ;

CREATE INDEX ACCINST_CL_PAYER_IND_I
   ON II_ACCINST_CONT_LINKS (PAYER_IND ASC)
   ;

CREATE INDEX ACCINST_CONT_FC_FK_I
   ON II_ACCINST_CONT_LINKS (FMMI_CUSTOMER_NUMBER ASC)
   ;

ALTER TABLE II_ACCINST_CONT_LINKS
  ADD CONSTRAINT ACCINST_CL_ACCINST_FK FOREIGN KEY (ACCINST_CN)
  REFERENCES ACCPLISHMENT_INSTRUMENTS (CN)  
  ON DELETE CASCADE;
