CREATE TABLE II_CONTACTS
(
   CN                    VARCHAR(34)    NOT NULL PRIMARY KEY,
   OBJ_TECH              VARCHAR(30)    NOT NULL,
   OBJ_NAME              VARCHAR(30)    NOT NULL,
   OBJ_CLASS             VARCHAR(30)    NOT NULL,
   ID                    VARCHAR(30)    NOT NULL,
   CREATED_BY            VARCHAR(30)    NOT NULL,
   CREATED_DATE          DATE                 NOT NULL,
   CREATED_IN_INSTANCE   NUMERIC(6)            NOT NULL,
   TRANS_ID              VARCHAR(34),
   NAME                  VARCHAR(120),
   MASTER_SITE           NUMERIC(6),
   REMARKS               VARCHAR(255),
   MODIFIED_BY           VARCHAR(30),
   MODIFIED_DATE         DATE,
   MODIFIED_IN_INSTANCE  NUMERIC(6),
   SECURITY_ID           VARCHAR(30),
   AGENCY_CODE           VARCHAR(4)     DEFAULT '11' NOT NULL,
   ADMIN_ORG_IND         VARCHAR(1)     DEFAULT 'N' NOT NULL,
   EIN                   VARCHAR(40),
   DUNS                  VARCHAR(40),
   FAADS_CN              VARCHAR(34),
   FFIS_VENDOR_STATUS    VARCHAR(40),
   ALC_CODE              VARCHAR(40),
   PARENT_DUNS           VARCHAR(40),
   DUNS_CONFIDENCE_CD    VARCHAR(2),
   INTERNATIONAL         VARCHAR(1)     DEFAULT 'N',
   ARCHIVED_FLAG         VARCHAR(1)     DEFAULT 'N' NOT NULL,
   OFFICE_HOURS          VARCHAR(300),
   CONSTRAINT CK_UC_19548_ID CHECK (        ID= upper(ID)        ),
   CONSTRAINT II_ADMIN_ORG_IND_CK CHECK (ADMIN_ORG_IND in ('Y','N','F')),
   CHECK (archived_flag IN ('Y', 'N'))
)
;

CREATE INDEX II_CONTS_IDX
   ON II_CONTACTS (ADMIN_ORG_IND ASC, ID ASC, CN ASC)
   ;

CREATE INDEX CONT_OBJ_FK_I
   ON II_CONTACTS (OBJ_TECH ASC, OBJ_NAME ASC, OBJ_CLASS ASC)
   ;

CREATE INDEX II_CONT_NAME_I
   ON II_CONTACTS (NAME ASC)
   ;

CREATE INDEX CONT_ADMIN_ORG_IND_I
   ON II_CONTACTS (ADMIN_ORG_IND ASC)
   ;

CREATE INDEX II_CONT_FAADS_FK177_IDX
   ON II_CONTACTS (FAADS_CN ASC)
   ;

CREATE INDEX II_CONT_OBJNAME_ID_NAME_CN_I
   ON II_CONTACTS (OBJ_NAME ASC, ID ASC, NAME ASC, CN ASC)
   ;

CREATE INDEX II_CONTACTS_DUNS_IDX
   ON II_CONTACTS (CN ASC, DUNS ASC, ID ASC)
   ;

CREATE INDEX II_CONT_ID_I
   ON II_CONTACTS (ID ASC)
   ;

ALTER TABLE II_CONTACTS
   ADD CONSTRAINT CONT_CONT2_UK UNIQUE (OBJ_TECH, OBJ_NAME, OBJ_CLASS, ID, TRANS_ID);

CREATE INDEX CONT_TRANS_FK_I
   ON II_CONTACTS (TRANS_ID ASC)
   ;

CREATE INDEX CONT_AGC_I
   ON II_CONTACTS (AGENCY_CODE ASC)
   ;

CREATE INDEX CONT_OBJ_NAME_ID_I
   ON II_CONTACTS (OBJ_NAME ASC, ID ASC)
   ;
