CREATE TABLE II_GA_NOTES
(
   CN                    VARCHAR(34)     NOT NULL,
   GRANT_CN              VARCHAR(34)     NOT NULL,
   NOTE_BY               VARCHAR(30)     NOT NULL,
   NOTE_DATE             DATE                  NOT NULL,
   COMMENTS              VARCHAR(2000)   NOT NULL,
   CREATED_BY            VARCHAR(30)     NOT NULL,
   CREATED_DATE          DATE                  NOT NULL,
   CREATED_IN_INSTANCE   NUMERIC(6)             NOT NULL,
   MODIFIED_BY           VARCHAR(30),
   MODIFIED_DATE         DATE,
   MODIFIED_IN_INSTANCE  NUMERIC(6),
   NOTE_TYPE             VARCHAR(50),
   EMAIL_TO              VARCHAR(500),
   EMAIL_DATE            DATE,
   LAST_UPDATE           DATE                  DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX GA_NOTES_CN_IDX ON II_GA_NOTES (CN);

ALTER TABLE II_GA_NOTES
   ADD CONSTRAINT II_GA_NOTES_PK
   PRIMARY KEY USING INDEX GA_NOTES_CN_IDX;
