#!/usr/bin/python3

import sys

# To build: a script that validates the ADRs are
# in the right format.

# Some criteria:
#
#  - Status is within [accepted, proposed, rejected, perhaps a few others]
#  - Date format
#  - Structure of history and people
#  - Section headers are all valid
#  - Optional "amends" key takes a list

# Also to do:
# - Build a main Markdown file `history.md` that includes just the titles,
#     descriptions, and dates for skimming.
# - Add this script into the CI process.

print("Not yet implemented")
sys.exit(1)
