global:
  application_name: ga
  branch: null
  default_ec2_keyname: terraformnew
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-gov-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
