branch-defaults:
  default:
    environment: development
    group_suffix: null
global:
  application_name: nrm-ga
  branch: null
  default_ec2_keyname: neil.martinsen-burrell
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
